### ISSUE TITLE
Preconfiguring CouchDB details behind a passworded server

### ISSUE THREAD

**Issue by kwadroke** [shellyln/kanban-board-app#2]
How do you pre-configure the Settings to point to a CouchDB  so other users/browsers can access the online database?

I understand if there's not some sort of authentication in front of the site others can modify the boards. I will be putting this in a passworded subfolder.

**Comment by shellyln** [comment]
Hi, @kwadroke !

This app is designed to be shared boards by trusted users only. Normally, operate with one user ID and password.
However, you may be able to operate with multiple IDs with different privileges.

If you are using `IBM Cloudant`, you can perform simple access control (`_admin`/`_reader`/`_writer`/`_replicator`) by issuing per-DB API keys from Cloudant dashboard.

_Note: This app is built on the assumption that the user have both `_reader`+`_writer` permissions._

The API secret will be the password.

Otherwise, if you want to use plain CouchDB, see for example the following documentation:
https://docs.couchdb.org/en/master/api/database/security.html
https://stackoverflow.com/questions/4055450/couchdb-authorization-on-a-per-database-basis

**Comment by kwadroke** [comment]
More looking to have a single user with the login pre-set in the page without having to set it on each browser/user.

**Comment by shellyln** [comment]
Hi, @kwadroke .

That’s a good point, but I do not want this app to be configured as a service, including the use of IDaaS.
